<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Klinik;

class KlinikSampleSeeder extends Seeder
{
    public function run(): void
    {
        $sampleKliniks = [
            // KLINIK DENGAN WEBSITE RESMI
            [
                'nama' => 'Erha Ultimate Jambi',
                'alamat' => 'Jl. Sultan Agung No. 123, Kota Jambi',
                'latitude' => -1.5961,
                'longitude' => 103.6231,
                'jam_operasional' => 'Senin-Sabtu: 09:00-18:00, Minggu: 10:00-16:00',
                'telepon' => '0741-123456',
                'email' => 'jambi@erha.co.id',
                'instagram' => 'erha_ultimate',
                'website' => 'https://erha.co.id',
                'status' => 'approved',
                'deskripsi' => 'Klinik kecantikan terpercaya dengan teknologi terdepan dan dokter berpengalaman. Brand besar dengan standar internasional.',
                'min_price' => 150000,
                'max_price' => 2500000,
                'services' => ['facial_acne', 'facial_brightening', 'chemical_peel', 'microneedling', 'laser_treatment', 'anti_aging']
            ],
            [
                'nama' => 'Natasha Skin Care Jambi',
                'alamat' => 'Jl. R.E. Martadinata No. 45, Pasar Jambi, Kota Jambi',
                'latitude' => -1.6092,
                'longitude' => 103.6095,
                'jam_operasional' => 'Senin-Jumat: 08:00-17:00, Sabtu: 09:00-15:00',
                'telepon' => '0741-987654',
                'email' => 'jambi@natasha-skincare.com',
                'instagram' => 'natashajambi',
                'facebook' => 'NatashaSkinCareJambi',
                'website' => 'https://natasha-skincare.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik estetika modern dengan layanan facial premium dan treatment anti-aging. Memberikan solusi kecantikan terbaik dengan harga terjangkau.',
                'min_price' => 75000,
                'max_price' => 1500000,
                'services' => ['facial_basic', 'facial_acne', 'facial_brightening', 'chemical_peel', 'vitamin_injection', 'hydrafacial']
            ],
            [
                'nama' => 'ZAP Clinic Jambi',
                'alamat' => 'Jl. Ahmad Yani No. 88, The Hok, Kota Jambi',
                'latitude' => -1.6143,
                'longitude' => 103.6189,
                'jam_operasional' => 'Senin-Sabtu: 10:00-20:00',
                'telepon' => '0741-456789',
                'email' => 'jambi@zapclinic.com',
                'instagram' => 'zapclinic_official',
                'website' => 'https://zapclinic.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik premium dengan 100+ outlet di Indonesia dan 15+ tahun pengalaman. Treatment eksklusif dengan teknologi terdepan.',
                'min_price' => 199000,
                'max_price' => 5000000,
                'services' => ['laser_treatment', 'botox', 'filler', 'facial_premium', 'anti_aging', 'body_treatment']
            ],

            [
                'nama' => 'VZ Skin Care',
                'alamat' => 'Jl. Prof. Dr. Sri Soedewi MS No. 12, Legok, Kota Jambi',
                'latitude' => -1.6201,
                'longitude' => 103.6076,
                'jam_operasional' => 'Senin-Sabtu: 08:30-17:30',
                'telepon' => '0741-789123',
                'email' => 'vz.skincare.jambi@gmail.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik perawatan kulit dengan pendekatan personal dan teknologi modern. Mengutamakan hasil natural dan aman.',
                'min_price' => 120000,
                'max_price' => 1800000,
                'services' => ['facial_premium', 'facial_acne', 'facial_brightening', 'vitamin_injection', 'chemical_peel', 'microneedling']
            ],

            // KLINIK DENGAN MEDIA SOSIAL AKTIF
            [
                'nama' => 'Klinik Kecantikan Athena Jambi',
                'alamat' => 'Jl. Letjen Suprapto No. 25, Telanaipura, Kota Jambi',
                'latitude' => -1.6045,
                'longitude' => 103.6158,
                'jam_operasional' => 'Senin-Jumat: 10:00-19:00, Sabtu: 09:00-17:00',
                'telepon' => '0741-654321',
                'email' => 'athena.jambi@gmail.com',
                'facebook' => 'Athena Clinic Jambi',
                'status' => 'approved',
                'deskripsi' => 'Klinik kecantikan dengan konsep Yunani kuno, menggabungkan kearifan klasik dengan teknologi modern.',
                'min_price' => 150000,
                'max_price' => 1500000,
                'services' => ['facial_brightening', 'chemical_peel', 'microneedling', 'vitamin_injection', 'facial_acne', 'anti_aging']
            ],
            [
                'nama' => 'Aira Skin Clinic',
                'alamat' => 'Jl. Pangeran Hidayat No. 89, Arab Melayu, Kota Jambi',
                'latitude' => -1.5923,
                'longitude' => 103.6187,
                'jam_operasional' => 'Senin-Minggu: 09:00-20:00',
                'telepon' => '0741-987321',
                'email' => 'aira.skin.jambi@gmail.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik kulit dengan treatment revolusioner dan hasil yang mengagumkan. Spesialisasi facial dan perawatan anti-aging.',
                'min_price' => 100000,
                'max_price' => 2000000,
                'services' => ['facial_brightening', 'hydrafacial', 'microneedling', 'vitamin_injection', 'facial_acne', 'anti_aging']
            ],
            [
                'nama' => 'Skinframe Jambi',
                'alamat' => 'Jl. Arief Rahman Hakim No. 156, Simpang Kawat, Kota Jambi',
                'latitude' => -1.5834,
                'longitude' => 103.6298,
                'jam_operasional' => 'Senin-Sabtu: 08:00-18:00',
                'telepon' => '0741-456123',
                'email' => 'skinframe.jambi@yahoo.com',
                'facebook' => 'SkinFrame Jambi',
                'status' => 'approved',
                'deskripsi' => 'SkinFrame Clinic dengan teknologi frame terbaru untuk perawatan kulit. Mengutamakan keamanan dan hasil optimal.',
                'min_price' => 180000,
                'max_price' => 2500000,
                'services' => ['facial_premium', 'laser_treatment', 'facial_acne', 'facial_brightening', 'chemical_peel', 'anti_aging']
            ],
            [
                'nama' => 'Al Two Aesthetic Clinic',
                'alamat' => 'Jl. Hayam Wuruk No. 234, Kota Jambi',
                'latitude' => -1.5789,
                'longitude' => 103.6412,
                'jam_operasional' => 'Senin-Jumat: 09:00-17:00, Sabtu: 09:00-15:00',
                'telepon' => '0741-567890',
                'email' => 'altwo.aesthetic@gmail.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik estetika dengan konsep modern dan minimalis. Menyediakan layanan comprehensive untuk semua kebutuhan kecantikan.',
                'min_price' => 120000,
                'max_price' => 1800000,
                'services' => ['facial_premium', 'body_treatment', 'facial_acne', 'facial_brightening', 'vitamin_injection', 'anti_aging']
            ],
            [
                'nama' => 'Nathalie Beauty Centre',
                'alamat' => 'Jl. Jenderal Sudirman No. 789, Jambi',
                'latitude' => -1.6012,
                'longitude' => 103.6234,
                'jam_operasional' => 'Senin-Sabtu: 08:00-17:00',
                'telepon' => '0741-111222',
                'email' => 'nathalie.beauty@gmail.com',
                'status' => 'approved',
                'deskripsi' => 'Beauty centre dengan pelayanan personal dan treatment berkualitas tinggi. Fokus pada kecantikan natural dan hasil memuaskan.',
                'min_price' => 75000,
                'max_price' => 1200000,
                'services' => ['facial_basic', 'facial_acne', 'facial_brightening', 'chemical_peel', 'microneedling', 'anti_aging']
            ],
            [
                'nama' => 'Everose Aesthetic Clinic',
                'alamat' => 'Jl. K.H. Ahmad Dahlan No. 445, Jambi',
                'latitude' => -1.5934,
                'longitude' => 103.6178,
                'jam_operasional' => 'Senin-Jumat: 09:00-18:00, Sabtu: 09:00-16:00',
                'telepon' => '0741-333444',
                'email' => 'everose.aesthetic@gmail.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik estetika dengan konsep rose yang elegan. Menawarkan perawatan premium dengan pelayanan berkelas.',
                'min_price' => 150000,
                'max_price' => 2000000,
                'services' => ['facial_premium', 'facial_acne', 'facial_brightening', 'chemical_peel', 'microneedling', 'anti_aging']
            ],
            [
                'nama' => 'Bening\'s Clinic Jambi',
                'alamat' => 'Jl. Dr. Sutomo No. 567, Jambi',
                'latitude' => -1.6067,
                'longitude' => 103.6145,
                'jam_operasional' => 'Setiap hari: 10:00-21:00',
                'telepon' => '0741-555666',
                'email' => 'benings.clinic.jambi@yahoo.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik dengan konsep bening dan jernih. Menghadirkan kecantikan natural dengan teknologi modern.',
                'min_price' => 100000,
                'max_price' => 1500000,
                'services' => ['facial_basic', 'facial_acne', 'facial_brightening', 'chemical_peel', 'microneedling', 'anti_aging']
            ],
            [
                'nama' => 'SKIN+ SLIM+ Clinic Jambi',
                'alamat' => 'Jl. Diponegoro No. 890, Jambi',
                'latitude' => -1.5856,
                'longitude' => 103.6267,
                'jam_operasional' => 'Senin-Sabtu: 09:00-19:00',
                'telepon' => '0741-777888',
                'email' => 'skinslim.jambi@clinic.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik spesialisasi perawatan kulit dan slimming. Kombinasi treatment skin care dan body contouring.',
                'min_price' => 125000,
                'max_price' => 1800000,
                'services' => ['facial_premium', 'body_treatment', 'facial_acne', 'facial_brightening', 'vitamin_injection', 'anti_aging']
            ],
            [
                'nama' => 'Naavagreen Jambi',
                'alamat' => 'Jl. Gajah Mada No. 123, Jambi',
                'latitude' => -1.5998,
                'longitude' => 103.6201,
                'jam_operasional' => 'Senin-Minggu: 08:00-20:00',
                'telepon' => '0741-999000',
                'email' => 'naavagreen.jambi@clinic.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik dengan konsep green dan natural. Treatment organik dengan bahan-bahan alami untuk hasil optimal.',
                'min_price' => 140000,
                'max_price' => 2200000,
                'services' => ['facial_basic', 'facial_acne', 'facial_brightening', 'chemical_peel', 'microneedling', 'anti_aging']
            ],
            [
                'nama' => 'Dermaperfect Skin & Beauty Center',
                'alamat' => 'Jl. Veteran No. 456, Jambi',
                'latitude' => -1.5912,
                'longitude' => 103.6289,
                'jam_operasional' => 'Senin-Sabtu: 09:00-18:00',
                'telepon' => '0741-111333',
                'email' => 'dermaperfect.jambi@gmail.com',
                'status' => 'approved',
                'deskripsi' => 'Beauty center dengan teknologi dermatologi perfect. Mengutamakan hasil sempurna dan kepuasan pelanggan.',
                'min_price' => 110000,
                'max_price' => 1600000,
                'services' => ['facial_medical', 'laser_treatment', 'botox', 'filler', 'chemical_peel', 'anti_aging']
            ],
            [
                'nama' => 'Shintia Beauty Clinic',
                'alamat' => 'Jl. Sultan Thaha No. 789, Jambi',
                'latitude' => -1.6023,
                'longitude' => 103.6156,
                'jam_operasional' => 'Senin-Jumat: 10:00-19:00, Sabtu-Minggu: 09:00-17:00',
                'telepon' => '0741-222555',
                'email' => 'shintia.beauty@center.com',
                'status' => 'approved',
                'deskripsi' => 'Beauty clinic dengan pelayanan personal dari Shintia. Treatment berkualitas tinggi dengan hasil memuaskan.',
                'min_price' => 160000,
                'max_price' => 2500000,
                'services' => ['signature_treatment', 'beauty_personal', 'facial_exclusive', 'premium_care', 'diamond_facial', 'gold_treatment', 'platinum_therapy']
            ],
            [
                'nama' => 'Rafika Beauty Center',
                'alamat' => 'Jl. Pahlawan No. 345, Jambi',
                'latitude' => -1.5845,
                'longitude' => 103.6323,
                'jam_operasional' => 'Setiap hari: 09:00-21:00',
                'telepon' => '0741-444777',
                'email' => 'rafika.beauty@clinic.co.id',
                'status' => 'approved',
                'deskripsi' => 'Beauty center dengan keahlian khusus Rafika dalam menciptakan kecantikan natural.',
                'min_price' => 130000,
                'max_price' => 1900000,
                'services' => ['glow_treatment', 'beauty_expert', 'natural_enhancement', 'signature_facial', 'brightening_infusion', 'radiance_therapy', 'luminous_facial']
            ],
            [
                'nama' => 'Klinik Axella Aesthetic Jambi',
                'alamat' => 'Jl. Imam Bonjol No. 678, Jambi',
                'latitude' => -1.6089,
                'longitude' => 103.6112,
                'jam_operasional' => 'Senin-Sabtu: 08:30-18:30',
                'telepon' => '0741-666999',
                'email' => 'axella.aesthetic.jambi@gmail.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik estetika Axella dengan teknologi terdepan. Treatment professional dengan hasil yang memuaskan.',
                'min_price' => 105000,
                'max_price' => 1400000,
                'services' => ['aesthetic_care', 'modern_facial', 'beauty_technology', 'skin_enhancement', 'ultrasonic_facial', 'led_therapy', 'oxygen_infusion']
            ],
            [
                'nama' => 'Wiyandra Beauty',
                'alamat' => 'Jl. Sutomo No. 901, Jambi',
                'latitude' => -1.5923,
                'longitude' => 103.6245,
                'jam_operasional' => 'Senin-Jumat: 09:00-17:00, Sabtu: 09:00-15:00',
                'telepon' => '0741-888111',
                'email' => 'wiyandra.beauty@gmail.com',
                'status' => 'approved',
                'deskripsi' => 'Beauty clinic Wiyandra dengan konsep modern dan elegan. Menghadirkan kecantikan dengan sentuhan personal.',
                'min_price' => 145000,
                'max_price' => 2100000,
                'services' => ['signature_treatment', 'beauty_modern', 'elegant_treatment', 'personal_care', 'luxury_facial', 'premium_skincare', 'anti_aging_facial']
            ],
            [
                'nama' => 'Kristie Aesthetic Clinic Jambi',
                'alamat' => 'Jl. Basuki Rahmat No. 234, Jambi',
                'latitude' => -1.6034,
                'longitude' => 103.6189,
                'jam_operasional' => 'Setiap hari: 10:00-20:00',
                'telepon' => '0741-222777',
                'email' => 'kristie.aesthetic@jambi.co.id',
                'status' => 'approved',
                'deskripsi' => 'Klinik estetika Kristie dengan keanggunan dan profesionalisme. Treatment mewah dengan hasil optimal.',
                'min_price' => 135000,
                'max_price' => 1750000,
                'services' => ['elegance_treatment', 'aesthetic_professional', 'luxury_treatment', 'beauty_enhancement', 'diamond_peel', 'collagen_therapy', 'vitamin_injection']
            ],
            [
                'nama' => 'Lafour Aesthetic Clinic',
                'alamat' => 'Jl. Ahmad Yani No. 567, Jambi',
                'latitude' => -1.5967,
                'longitude' => 103.6278,
                'jam_operasional' => 'Senin-Sabtu: 09:00-19:00',
                'telepon' => '0741-555333',
                'email' => 'lafour.aesthetic@center.com',
                'status' => 'approved',
                'deskripsi' => 'Aesthetic clinic Lafour dengan teknologi terdepan. Memberikan treatment eksklusif dengan hasil menawan.',
                'min_price' => 115000,
                'max_price' => 1650000,
                'services' => ['signature_treatment', 'aesthetic_advanced', 'exclusive_treatment', 'modern_beauty', 'laser_therapy', 'microneedling', 'chemical_peel']
            ],
            [
                'nama' => 'Klinik Pratama Letrysa',
                'alamat' => 'Jl. Kartini No. 890, Jambi',
                'latitude' => -1.5889,
                'longitude' => 103.6334,
                'jam_operasional' => 'Senin-Minggu: 08:00-20:00',
                'telepon' => '0741-777222',
                'email' => 'letrysa.pratama@clinic.co.id',
                'status' => 'approved',
                'deskripsi' => 'Klinik pratama Letrysa dengan pelayanan medis dan estetika. Kombinasi kesehatan dan kecantikan.',
                'min_price' => 175000,
                'max_price' => 2800000,
                'services' => ['medical_aesthetic', 'health_beauty', 'pratama_care', 'wellness_treatment', 'medical_facial', 'health_consultation', 'dermatology_treatment']
            ],
            [
                'nama' => 'Elitha Aesthetic Clinic',
                'alamat' => 'Jl. Hayam Wuruk No. 432, Jambi',
                'latitude' => -1.5778,
                'longitude' => 103.6401,
                'jam_operasional' => 'Senin-Sabtu: 09:00-18:00',
                'telepon' => '0741-123789',
                'email' => 'elitha.aesthetic@gmail.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik estetika Elitha dengan pelayanan premium dan teknologi modern.',
                'min_price' => 140000,
                'max_price' => 1900000,
                'services' => ['glow_treatment', 'premium_aesthetic', 'modern_treatment', 'beauty_care', 'hydrafacial', 'vitamin_infusion', 'brightening_therapy']
            ],
            [
                'nama' => 'SkinServ Clinic',
                'alamat' => 'Jl. R.E. Martadinata No. 654, Jambi',
                'latitude' => -1.6101,
                'longitude' => 103.6087,
                'jam_operasional' => 'Senin-Jumat: 08:00-17:00',
                'telepon' => '0741-456987',
                'email' => 'skinserv.clinic@yahoo.com',
                'status' => 'approved',
                'deskripsi' => 'SkinServ Clinic dengan layanan perawatan kulit terdepan dan teknologi inovatif.',
                'min_price' => 120000,
                'max_price' => 1700000,
                'services' => ['skin_service', 'advanced_skincare', 'facial_technology', 'skin_analysis', 'laser_treatment', 'acne_therapy', 'anti_aging']
            ],
            [
                'nama' => 'Liyan Aesthetic Clinic',
                'alamat' => 'Jl. Sultan Agung No. 876, Jambi',
                'latitude' => -1.5945,
                'longitude' => 103.6245,
                'jam_operasional' => 'Setiap hari: 10:00-21:00',
                'telepon' => '0741-789456',
                'email' => 'liyan.aesthetic@clinic.com',
                'status' => 'approved',
                'deskripsi' => 'Liyan Aesthetic Clinic dengan treatment khusus dan pelayanan personal yang memuaskan.',
                'min_price' => 130000,
                'max_price' => 1800000,
                'services' => ['signature_treatment', 'aesthetic_special', 'personal_treatment', 'beauty_enhancement', 'facial_premium', 'skincare_therapy', 'rejuvenation']
            ],
            [
                'nama' => 'Klinik Kecantikan Glow Expert',
                'alamat' => 'Jl. Pangeran Hidayat No. 321, Jambi',
                'latitude' => -1.5912,
                'longitude' => 103.6198,
                'jam_operasional' => 'Senin-Sabtu: 09:00-19:00',
                'telepon' => '0741-321987',
                'email' => 'glowexpert.jambi@gmail.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik spesialis glow dengan keahlian menciptakan kulit bercahaya natural.',
                'min_price' => 125000,
                'max_price' => 1600000,
                'services' => ['expert_glow', 'radiance_treatment', 'brightening_therapy', 'glow_enhancement', 'luminous_facial', 'vitamin_c_treatment', 'skin_brightening']
            ],
            [
                'nama' => 'Els Clinic',
                'alamat' => 'Jl. Letjen Suprapto No. 543, Jambi',
                'latitude' => -1.6056,
                'longitude' => 103.6167,
                'jam_operasional' => 'Senin-Jumat: 10:00-18:00, Sabtu: 09:00-16:00',
                'telepon' => '0741-654987',
                'email' => 'els.clinic.jambi@yahoo.com',
                'status' => 'approved',
                'deskripsi' => 'Els Clinic dengan pelayanan berkualitas dan treatment modern untuk kecantikan optimal.',
                'min_price' => 110000,
                'max_price' => 1500000,
                'services' => ['els_treatment', 'modern_beauty', 'facial_care', 'skin_therapy', 'hydrafacial', 'acne_treatment', 'anti_aging_care']
            ],
            [
                'nama' => 'Emerald Clinic Jambi',
                'alamat' => 'Jl. Dr. Sutomo No. 765, Jambi',
                'latitude' => -1.6078,
                'longitude' => 103.6134,
                'jam_operasional' => 'Senin-Minggu: 08:00-20:00',
                'telepon' => '0741-987321',
                'email' => 'emerald.clinic@jambi.co.id',
                'status' => 'approved',
                'deskripsi' => 'Emerald Clinic dengan treatment premium seperti permata zamrud yang berharga.',
                'min_price' => 155000,
                'max_price' => 2200000,
                'services' => ['glow_treatment', 'precious_treatment', 'gem_facial', 'luxury_care', 'diamond_facial', 'emerald_therapy', 'premium_skincare']
            ],
            [
                'nama' => 'HiSkin Jambi',
                'alamat' => 'Jl. Gajah Mada No. 987, Jambi',
                'latitude' => -1.6009,
                'longitude' => 103.6212,
                'jam_operasional' => 'Senin-Sabtu: 09:00-18:00',
                'telepon' => '0741-147258',
                'email' => 'hiskin.jambi@clinic.com',
                'status' => 'approved',
                'deskripsi' => 'HiSkin Clinic dengan teknologi tinggi untuk perawatan kulit terdepan.',
                'min_price' => 135000,
                'max_price' => 1850000,
                'services' => ['skin_technology', 'advanced_treatment', 'modern_facial', 'skin_innovation', 'laser_therapy', 'ipl_treatment', 'rf_microneedling']
            ],
            [
                'nama' => 'Klinik Kecantikan Kusuma',
                'alamat' => 'Jl. Veteran No. 234, Jambi',
                'latitude' => -1.5923,
                'longitude' => 103.6298,
                'jam_operasional' => 'Setiap hari: 09:00-21:00',
                'telepon' => '0741-369258',
                'email' => 'kusuma.beauty@gmail.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik Kusuma dengan konsep bunga yang mekar indah, memberikan kecantikan natural.',
                'min_price' => 115000,
                'max_price' => 1650000,
                'services' => ['natural_bloom', 'natural_beauty', 'floral_treatment', 'organic_care', 'herbal_facial', 'botanical_therapy', 'aromatherapy']
            ],
            [
                'nama' => 'Sha Aesthetic Clinic',
                'alamat' => 'Jl. Pahlawan No. 567, Jambi',
                'latitude' => -1.5834,
                'longitude' => 103.6334,
                'jam_operasional' => 'Senin-Sabtu: 08:30-18:30',
                'telepon' => '0741-852741',
                'email' => 'sha.aesthetic@clinic.co.id',
                'status' => 'approved',
                'deskripsi' => 'Sha Aesthetic dengan treatment estetika terdepan dan pelayanan professional.',
                'min_price' => 145000,
                'max_price' => 2000000,
                'services' => ['signature_treatment', 'aesthetic_premium', 'professional_care', 'beauty_treatment', 'facial_exclusive', 'luxury_therapy', 'premium_facial']
            ],
            [
                'nama' => 'Klinik Kei Medika',
                'alamat' => 'Jl. Imam Bonjol No. 890, Jambi',
                'latitude' => -1.6098,
                'longitude' => 103.6123,
                'jam_operasional' => 'Senin-Jumat: 09:00-17:00, Sabtu: 09:00-15:00',
                'telepon' => '0741-741963',
                'email' => 'kei.medika@jambi.com',
                'status' => 'approved',
                'deskripsi' => 'Kei Medika dengan pendekatan medis dan estetika untuk kesehatan dan kecantikan optimal.',
                'min_price' => 125000,
                'max_price' => 1750000,
                'services' => ['medical_beauty', 'health_aesthetic', 'medika_care', 'wellness_treatment', 'medical_facial', 'health_consultation', 'therapeutic_care']
            ],
            [
                'nama' => 'Jambi Skin Centre',
                'alamat' => 'Jl. Sultan Thaha No. 432, Jambi',
                'latitude' => -1.6034,
                'longitude' => 103.6167,
                'jam_operasional' => 'Senin-Minggu: 08:00-20:00',
                'telepon' => '0741-159357',
                'email' => 'jambi.skin.centre@yahoo.com',
                'status' => 'approved',
                'deskripsi' => 'Jambi Skin Centre sebagai pusat perawatan kulit terlengkap di Jambi.',
                'min_price' => 140000,
                'max_price' => 1900000,
                'services' => ['skin_center', 'comprehensive_care', 'dermatology_treatment', 'skin_specialist', 'medical_skincare', 'acne_therapy', 'anti_aging_treatment']
            ],
            [
                'nama' => 'Zaira Skincare Jambi',
                'alamat' => 'Jl. Kartini No. 654, Jambi',
                'latitude' => -1.5898,
                'longitude' => 103.6345,
                'jam_operasional' => 'Senin-Sabtu: 09:00-19:00',
                'telepon' => '0741-753951',
                'email' => 'zaira.skincare.jambi@gmail.com',
                'status' => 'approved',
                'deskripsi' => 'Zaira Skincare dengan produk dan treatment khusus untuk berbagai jenis kulit.',
                'min_price' => 110000,
                'max_price' => 1550000,
                'services' => ['skincare_premium', 'custom_treatment', 'skin_consultation', 'personalized_care', 'facial_analysis', 'bespoke_skincare', 'customized_facial']
            ],
            [
                'nama' => 'Kliniku by Dr. Dwi Astuti',
                'alamat' => 'Jl. Ahmad Yani No. 321, Jambi',
                'latitude' => -1.5976,
                'longitude' => 103.6289,
                'jam_operasional' => 'Setiap hari: 10:00-21:00',
                'telepon' => '0741-951753',
                'email' => 'kliniku.drdwiastuti@clinic.com',
                'status' => 'approved',
                'deskripsi' => 'Kliniku by Dr. Dwi Astuti dengan pelayanan dokter spesialis dan treatment professional.',
                'min_price' => 160000,
                'max_price' => 2300000,
                'services' => ['doctor_treatment', 'specialist_care', 'medical_aesthetic', 'professional_service', 'dermatologist_consultation', 'medical_facial', 'clinical_skincare']
            ],
            [
                'nama' => 'Klinik Eunoia by Dr. Melisa Juni',
                'alamat' => 'Jl. Basuki Rahmat No. 789, Jambi',
                'latitude' => -1.6045,
                'longitude' => 103.6198,
                'jam_operasional' => 'Senin-Sabtu: 08:00-18:00',
                'telepon' => '0741-357159',
                'email' => 'eunoia.drmelisajuni@gmail.com',
                'status' => 'approved',
                'deskripsi' => 'Klinik Eunoia by Dr. Melisa Juni dengan konsep beautiful thinking dan treatment inovatif.',
                'min_price' => 170000,
                'max_price' => 2400000,
                'services' => ['wellness_treatment', 'innovative_care', 'doctor_specialist', 'beautiful_mind', 'holistic_therapy', 'mindful_skincare', 'wellness_facial']
            ],
            [
                'nama' => 'Dr. Ria Aesthetic Clinic',
                'alamat' => 'Jl. Diponegoro No. 456, Jambi',
                'latitude' => -1.5867,
                'longitude' => 103.6278,
                'jam_operasional' => 'Senin-Jumat: 08:00-17:00, Sabtu: 09:00-15:00',
                'telepon' => '0741-159753',
                'email' => 'drria.aesthetic@clinic.co.id',
                'status' => 'approved',
                'deskripsi' => 'Dr. Ria Aesthetic Clinic dengan pelayanan dokter spesialis dan treatment estetika terdepan.',
                'min_price' => 150000,
                'max_price' => 2100000,
                'services' => ['aesthetic_treatment', 'medical_facial', 'doctor_consultation', 'beauty_enhancement', 'dermatology_care', 'anti_aging_treatment', 'skin_rejuvenation']
            ]
        ];

        foreach ($sampleKliniks as $klinik) {
            Klinik::create($klinik);
        }
    }
}
